export const COMPILATION_METADATA_TOKENS = {
  HEADER: 'Auto-generated by Clawject. Alterations of it and the subsequent property can cause unexpected behavior.'.toUpperCase(),
  LINE_START: '* ',
  LINE_END: ' *\n',
};
