export enum BeanKind {
    METHOD = 'METHOD',
    PROPERTY = 'PROPERTY',
    ARROW_FUNCTION = 'ARROW_FUNCTION',
    EXPRESSION = 'EXPRESSION',
    LIFECYCLE_METHOD = 'LIFECYCLE_METHOD',
    LIFECYCLE_ARROW_FUNCTION = 'LIFECYCLE_ARROW_FUNCTION',
}
